apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
spec:
  bootstrap:
    initdb:
      database: awx
      owner: awx
  certificates:
    serverCASecret: postgresql-tls
    serverTLSSecret: postgresql-tls
  enableSuperuserAccess: true
  imageName: ghcr.io/cloudnative-pg/postgresql:16.3-bookworm
  instances: 1
  storage:
    size: 128Mi
