apiVersion: v1
kind: Secret
metadata:
  name: postgresql-superuser
  annotations:
    custom.argocd.argoproj.io/ignore-path: ".data.*"
type: kubernetes.io/basic-auth
data:
  password: ""
  username: ""
